# encoding: utf-8
class MappingKeyword
  BB = [
    {:url => 'http://www.coopertire.com.cn/products_list_pcr.htm',
     :patern => ['SUV|4X4','SUV和4X4','SUV和4X4(轮胎)?','(4X4|SUV)轮胎']},
    {:url => 'http://www.coopertire.com.cn/brand_position.htm',
     :patern => '越野轮胎'},
    {:url => 'http://www.coopertire.com.cn/products_list_pcr.htm',
     :patern => '轿车轮胎'} ,
    {:url => 'http://www.coopertire.com.cn/products_list_winter.htm',
     :patern => '冬季轮胎'},
    {:url => 'http://www.coopertire.com.cn/stt_detail.htm',
     :patern => 'DISCOVERER STT'},
    {:url => 'http://www.coopertire.com.cn/stmaxx_detail.htm', 
     :patern => 'DISCOVERER STMAXX'},
    {:url => 'http://www.coopertire.com.cn/at3_detail.htm', :patern => 'DISCOVERER AT3'},
    {:url => '', :patern => 'DISCOVERER ATR'},
    {:url => '', :patern => 'DISCOVERER ATS (SUV&LT)'},
    {:url =>'', :patern => 'DISCOVERER HTS'},
    {:url => '', :patern =>'ZEON XST-A' },
    {:url => '', :patern => 'ZEON 4XS'},
    {:url =>'', :patern => '驭动ZEON RS3-S'},
    {:url =>'', :patern =>  'ZEON RS3-S'},
    {:url => '', :patern => '驭行ZEON RS3-A'},
    {:url => '', :patern => 'ZEON RS3-A'},
    {:url =>'',  :patern => 'ZEON ASP'},
    {:url => '', :patern =>  'LIFELINER GLS'},
    {:url => '', :patern => 'ZEON ATP'},
    {'Weather Master SA2'},
    {'Weather Master S/T3'},
    {'Avon Ice Touring'},
    {'Weather Master S/T2'},
    {'Discoverer M+S'},{'本田'},{'crv'},{'本田crv'},
    {'本田crv轮胎'},{'标致'},{'408'},{'标致408'},{'标致408轮胎'},{'别克'},{'英朗'},{'别克英朗'},{'别克英朗轮胎'},
     {'大众','cc','大众cc','大众cc轮胎'},
{'奇瑞','a3','奇瑞a3','奇瑞a3轮胎'},
{'斯柯达','明锐','斯柯达明锐','斯柯达明锐轮胎'},
{'雪铁龙','c5','雪铁龙c5','雪铁龙c5轮胎'},
{'奥迪','a4','奥迪a4','奥迪a4轮胎','a6','奥迪a6','奥迪a6轮胎','q5','奥迪q5','奥迪q5轮胎','奥迪轮胎'},
{'宝马','x5','宝马x5','宝马x5轮胎','宝马','x6','宝马x6','宝马x6轮胎','宝马轮胎'},
{'保时捷轮胎'},{'奔驰轮胎'},{'悍马轮胎'},{'路虎轮胎',{'荣威轮胎'},{'夏利轮胎'},{'长城轮胎'},{'全球越野轮胎大师'}
  ]
end
