development: &development
  adapter: mysql2
  host: localhost
  username: root
  password: ""
  database: cooper

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password: ""
  database: cooper

production: &production
  adapter: mysql2
  host: localhost
  database: cooper
  username: root
  password: ""
