development: &development
  adapter: mysql2
  host: localhost
  username: coopertire
  password: "coopertire"
  database: coopertire

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password: "123456"
  database: cooper

production: &production
  adapter: mysql2
  host: localhost
  username: coopertire
  password: "coopertire"
  database: coopertire
