- patern:  ['SUV|4X4','SUV和4X4','SUV和4X4(轮胎)?','(4X4|SUV)轮胎']
  url: 'http://www.coopertire.com.cn/products_list_pcr.htm'
- patern: '越野轮胎'
  url: 'http://www.coopertire.com.cn/brand_position.htm'
- patern: '轿车轮胎'
  url: 'http://www.coopertire.com.cn/products_list_pcr.htm'
- patern: '冬季轮胎'
  url: 'http://www.coopertire.com.cn/products_list_winter.htm'
- patern: 'DISCOVERER STT'
  url: 'http://www.coopertire.com.cn/stmaxx_detail.htm'
- patern: 'DISCOVERER STMAXX'
  url: 'http://www.coopertire.com.cn/at3_detail.htm'

- patern: 'DISCOVERER ATR'
  url: ''

- patern: 'DISCOVERER ATS (SUV&LT)'
  url: ''
- patern: 'DISCOVERER HTS'
  url: ''
- patern: 'ZEON XST-A'
  url: ''
- patern: 'ZEON 4XS'
  url: ''
- patern: '驭动ZEON RS3-S'
  url: ''
- patern: 'ZEON RS3-S'
  url: ''
- patern: '驭行ZEON RS3-A'
  url: ''
- patern: 'ZEON RS3-A'
  url: ''
- patern: 'ZEON ASP'
  url: ''
- patern: 'LIFELINER GLS'
  url: ''
- patern: 'ZEON ATP'
  url: ''
- patern: 'Weather Master SA2'
  url: ''
- patern: 'Weather Master S/T3'
  url: ''
- patern: 'Avon Ice Touring'
  url: ''
- patern: 'Weather Master S/T2'
  url: ''
- patern: 'Discoverer M+S'
  url: ''
- patern: '本田'
  url: ''
- patern: 'crv'
  url: ''
- patern: '本田crv'
  url: ''
- patern: '本田crv轮胎'
  url: ''
- patern: '标致'
  url: ''
- patern: '408'
  url: ''
- patern: '标致408'
  url: ''
- patern: '标致408轮胎'
  url: ''
- patern: '本田'
  url: ''
- patern: '本田'
  url: ''
- patern: '本田'
  url: ''
- patern: '本田'
  url: ''
- patern: '本田'
  url: ''
- patern: '本田'
  url: ''
- patern: '本田'
  url: ''
