- patern:  ['SUV|4X4','SUV和4X4','SUV和4X4(轮胎)?','(4X4|SUV)轮胎']
  url: 'http://www.coopertire.com.cn/products_list_pcr.htm'
- patern: '越野轮胎'
  url: 'http://www.coopertire.com.cn/brand_position.htm'
- patern: '轿车轮胎'
  url: 'http://www.coopertire.com.cn/products_list_pcr.htm'
- patern: '冬季轮胎'
  url: 'http://www.coopertire.com.cn/products_list_winter.htm'
- patern: 'DISCOVERER STT'
  url: 'http://www.coopertire.com.cn/stmaxx_detail.htm'
- patern: 'DISCOVERER STMAXX'
  url: 'http://www.coopertire.com.cn/at3_detail.htm'

- patern: 'DISCOVERER ATR'
  url: ''

- patern: 'DISCOVERER ATS (SUV&LT)'
  url: ''
- patern: 'DISCOVERER HTS'
  url: ''
- patern: ''
  url: ''
- patern: ''
  url: ''
- patern: ''
  url: ''
- patern: ''
  url: ''
- patern: ''
  url: ''
- patern: ''
  url: ''
- patern: ''
  url: ''
- patern: ''
  url: ''
- patern: ''
  url: ''
- patern: ''
  url: ''
